/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookreader;

import com.alee.laf.WebLookAndFeel;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author thusitha
 */
public class BookShelf extends javax.swing.JFrame {

    /**
     * Creates new form BookShelf
     */
    public int WINDOW_SIZE; //0-normal, 1-maximized, 2-minimize, 3-expand
    private Dimension DefaultSize=new Dimension(750, 400);
    public boolean MAINMENU = true;
    
    public BookShelf() {
        initComponents();
        
        //hide main menu at startup
        webPanel5.setVisible(false);
        
        //moving undecorae window using its component
        ComponentMover mover = new ComponentMover(BookShelf.class, webPanel2);
        addMouseListener(new DragListener());
        
        //resize undecorate window using its component
        ComponentResizer resizer = new ComponentResizer();
        ComponentResizer cr = new ComponentResizer();
        cr.setSnapSize(new Dimension(15, 15));
        cr.registerComponent(this);
        
        //window start in middle of the screen
        setLocationRelativeTo(null);
        
    }
    
    /////////////////
    //Window resize//
    /////////////////
    
    public void windowMaximizeOrRestore(){
            if(WINDOW_SIZE==0){//if normal then maximize both
                WINDOW_SIZE=1;
                setExtendedState(JFrame.MAXIMIZED_BOTH);
                try {
                    webLabel2.setIcon(new ImageIcon(getClass().getResource("/images/restore.png").toURI().getPath()));
                    setSize(Toolkit.getDefaultToolkit().getScreenSize().width,Toolkit.getDefaultToolkit().getScreenSize().height-30);
                } catch (URISyntaxException ex) {
                    Logger.getLogger(BookShelf.class.getName()).log(Level.SEVERE, null, ex);
                }
                setLocationRelativeTo(null);
            }else{//else make window normal
                WINDOW_SIZE=0;
                setExtendedState(JFrame.NORMAL);
                try {
                    webLabel2.setIcon(new ImageIcon(getClass().getResource("/images/maximize.png").toURI().getPath()));
                    setSize(DefaultSize);
                } catch (URISyntaxException ex) {
                    Logger.getLogger(BookShelf.class.getName()).log(Level.SEVERE, null, ex);
                }
                //setSize(DefaultSize);
                setLocationRelativeTo(null);
            }
    }
    
    public void windowExpand(){
            if(WINDOW_SIZE!=3){//if normal then maximize both
                WINDOW_SIZE=3;
                setExtendedState(JFrame.MAXIMIZED_BOTH);
                setSize(Toolkit.getDefaultToolkit().getScreenSize());
                setLocationRelativeTo(null);
            }else{//else make window normal
                WINDOW_SIZE=1;
                //setSize(DefaultSize);
                setExtendedState(JFrame.NORMAL);
                try {
                    webLabel2.setIcon(new ImageIcon(getClass().getResource("/images/maximize.png").toURI().getPath()));
                    setSize(DefaultSize);
                } catch (URISyntaxException ex) {
                    Logger.getLogger(BookShelf.class.getName()).log(Level.SEVERE, null, ex);
                }
                setLocationRelativeTo(null);
            }
    }
    
    ////////////////
    //
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        webPanel1 = new com.alee.laf.panel.WebPanel();
        webPanel2 = new com.alee.laf.panel.WebPanel();
        webLabel1 = new com.alee.laf.label.WebLabel();
        webLabel2 = new com.alee.laf.label.WebLabel();
        webLabel3 = new com.alee.laf.label.WebLabel();
        webLabel5 = new com.alee.laf.label.WebLabel();
        webLabel4 = new com.alee.laf.label.WebLabel();
        webLabel6 = new com.alee.laf.label.WebLabel();
        webPanel3 = new com.alee.laf.panel.WebPanel();
        webPanel4 = new com.alee.laf.panel.WebPanel();
        webPanel5 = new com.alee.laf.panel.WebPanel();
        webPanel9 = new com.alee.laf.panel.WebPanel();
        webButton1 = new com.alee.laf.button.WebButton();
        webPanel10 = new com.alee.laf.panel.WebPanel();
        webPanel6 = new com.alee.laf.panel.WebPanel();
        webPanel7 = new com.alee.laf.panel.WebPanel();
        webPanel8 = new com.alee.laf.panel.WebPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        webPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102)));

        webPanel2.setBackground(new java.awt.Color(255, 255, 255));
        webPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                webPanel2MouseClicked(evt);
            }
        });

        webLabel1.setBackground(new java.awt.Color(255, 255, 255));
        webLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        webLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        webLabel1.setMargin(new java.awt.Insets(5, 5, 5, 5));
        webLabel1.setOpaque(true);
        webLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                webLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                webLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                webLabel1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                webLabel1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                webLabel1MouseReleased(evt);
            }
        });

        webLabel2.setBackground(new java.awt.Color(255, 255, 255));
        webLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        webLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/maximize.png"))); // NOI18N
        webLabel2.setMargin(new java.awt.Insets(5, 5, 5, 5));
        webLabel2.setOpaque(true);
        webLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                webLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                webLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                webLabel2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                webLabel2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                webLabel2MouseReleased(evt);
            }
        });

        webLabel3.setBackground(new java.awt.Color(255, 255, 255));
        webLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        webLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minimize.png"))); // NOI18N
        webLabel3.setMargin(new java.awt.Insets(5, 5, 5, 5));
        webLabel3.setOpaque(true);
        webLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                webLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                webLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                webLabel3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                webLabel3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                webLabel3MouseReleased(evt);
            }
        });

        webLabel5.setBackground(new java.awt.Color(255, 194, 59));
        webLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        webLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bookshelf.png"))); // NOI18N
        webLabel5.setOpaque(true);
        webLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                webLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                webLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                webLabel5MouseExited(evt);
            }
        });

        webLabel4.setText("Axion Book Manger");

        webLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        webLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/expand.png"))); // NOI18N
        webLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                webLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout webPanel2Layout = new javax.swing.GroupLayout(webPanel2);
        webPanel2.setLayout(webPanel2Layout);
        webPanel2Layout.setHorizontalGroup(
            webPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, webPanel2Layout.createSequentialGroup()
                .addComponent(webLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(webLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(webLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(webLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(webLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(webLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        webPanel2Layout.setVerticalGroup(
            webPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(webLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(webLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(webLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(webLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(webPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(webLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(webLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        webPanel3.setBackground(new java.awt.Color(51, 51, 51));
        webPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                webPanel3MouseClicked(evt);
            }
        });

        webPanel5.setBackground(new java.awt.Color(255, 255, 255));

        webPanel9.setBackground(new java.awt.Color(116, 10, 0));

        webButton1.setText("webButton1");
        webButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webButton1ActionPerformed(evt);
            }
        });
        webPanel9.add(webButton1, java.awt.BorderLayout.PAGE_START);

        webPanel10.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout webPanel5Layout = new javax.swing.GroupLayout(webPanel5);
        webPanel5.setLayout(webPanel5Layout);
        webPanel5Layout.setHorizontalGroup(
            webPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(webPanel5Layout.createSequentialGroup()
                .addComponent(webPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(webPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
        );
        webPanel5Layout.setVerticalGroup(
            webPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(webPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
            .addComponent(webPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        webPanel6.setBackground(new java.awt.Color(204, 255, 204));

        webPanel7.setBackground(new java.awt.Color(255, 233, 140));

        webPanel8.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout webPanel6Layout = new javax.swing.GroupLayout(webPanel6);
        webPanel6.setLayout(webPanel6Layout);
        webPanel6Layout.setHorizontalGroup(
            webPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(webPanel6Layout.createSequentialGroup()
                .addComponent(webPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(webPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
        );
        webPanel6Layout.setVerticalGroup(
            webPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(webPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(webPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout webPanel4Layout = new javax.swing.GroupLayout(webPanel4);
        webPanel4.setLayout(webPanel4Layout);
        webPanel4Layout.setHorizontalGroup(
            webPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(webPanel4Layout.createSequentialGroup()
                .addComponent(webPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(webPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        webPanel4Layout.setVerticalGroup(
            webPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(webPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(webPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout webPanel3Layout = new javax.swing.GroupLayout(webPanel3);
        webPanel3.setLayout(webPanel3Layout);
        webPanel3Layout.setHorizontalGroup(
            webPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(webPanel3Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(webPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(3, 3, 3))
        );
        webPanel3Layout.setVerticalGroup(
            webPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(webPanel3Layout.createSequentialGroup()
                .addComponent(webPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(3, 3, 3))
        );

        javax.swing.GroupLayout webPanel1Layout = new javax.swing.GroupLayout(webPanel1);
        webPanel1.setLayout(webPanel1Layout);
        webPanel1Layout.setHorizontalGroup(
            webPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(webPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(webPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        webPanel1Layout.setVerticalGroup(
            webPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(webPanel1Layout.createSequentialGroup()
                .addComponent(webPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(webPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(webPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(webPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void webLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webLabel1MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_webLabel1MouseClicked

    private void webPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webPanel2MouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount()==2) {
            windowMaximizeOrRestore();
        }
    }//GEN-LAST:event_webPanel2MouseClicked

    private void webLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webLabel2MouseClicked
        // TODO add your handling code here:
        windowMaximizeOrRestore();
    }//GEN-LAST:event_webLabel2MouseClicked

    private void webLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webLabel3MouseClicked
        // TODO add your handling code here:
        
        setExtendedState(JFrame.ICONIFIED);
        try {
            webLabel2.setIcon(new ImageIcon(getClass().getResource("/images/maximize.png").toURI().getPath()));
            //setSize(Toolkit.getDefaultToolkit().getScreenSize().width,Toolkit.getDefaultToolkit().getScreenSize().height-30);
        } catch (URISyntaxException ex) {
            Logger.getLogger(BookShelf.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_webLabel3MouseClicked

    private void webPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webPanel3MouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount()==2) {
            windowMaximizeOrRestore();
        }
    }//GEN-LAST:event_webPanel3MouseClicked

    private void webLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webLabel3MouseEntered
        // TODO add your handling code here:
        webLabel3.setBackground(new Color(230, 230, 230));
    }//GEN-LAST:event_webLabel3MouseEntered

    private void webLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webLabel2MouseEntered
        // TODO add your handling code here:
        webLabel2.setBackground(new Color(230, 230, 230));
    }//GEN-LAST:event_webLabel2MouseEntered

    private void webLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webLabel1MouseEntered
        // TODO add your handling code here:
        webLabel1.setBackground(new Color(250, 100, 10));
    }//GEN-LAST:event_webLabel1MouseEntered

    private void webLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webLabel3MouseExited
        // TODO add your handling code here:
        webLabel3.setBackground(Color.white);
    }//GEN-LAST:event_webLabel3MouseExited

    private void webLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webLabel2MouseExited
        // TODO add your handling code here:
        webLabel2.setBackground(Color.white);
    }//GEN-LAST:event_webLabel2MouseExited

    private void webLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webLabel1MouseExited
        // TODO add your handling code here:
        webLabel1.setBackground(Color.white);
    }//GEN-LAST:event_webLabel1MouseExited

    private void webLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webLabel1MousePressed
        // TODO add your handling code here:
        webLabel1.setBackground(new Color(230, 80, 20));
    }//GEN-LAST:event_webLabel1MousePressed

    private void webLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webLabel3MousePressed
        // TODO add your handling code here:
        webLabel3.setBackground(new Color(210, 210, 210));
    }//GEN-LAST:event_webLabel3MousePressed

    private void webLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webLabel2MousePressed
        // TODO add your handling code here:
        webLabel2.setBackground(new Color(210, 210, 210));
    }//GEN-LAST:event_webLabel2MousePressed

    private void webLabel3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webLabel3MouseReleased
        // TODO add your handling code here:
        webLabel3.setBackground(new Color(230, 230, 230));
    }//GEN-LAST:event_webLabel3MouseReleased

    private void webLabel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webLabel2MouseReleased
        // TODO add your handling code here:
        webLabel2.setBackground(new Color(230, 230, 230));
    }//GEN-LAST:event_webLabel2MouseReleased

    private void webLabel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webLabel1MouseReleased
        // TODO add your handling code here:
        webLabel1.setBackground(Color.WHITE);
    }//GEN-LAST:event_webLabel1MouseReleased

    private void webLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webLabel6MouseClicked
        // TODO add your handling code here:
        windowExpand();
    }//GEN-LAST:event_webLabel6MouseClicked

    private void webLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webLabel5MouseClicked
        // TODO add your handling code here:
        if (MAINMENU) {
            MAINMENU=false;
            webPanel5.setVisible(true);
            webPanel6.setVisible(false);
            webLabel5.setBackground(Color.red);
        }else{
            MAINMENU=true;
            webPanel5.setVisible(false);
            webPanel6.setVisible(true);
            webLabel5.setBackground(Color.white);
        }
    }//GEN-LAST:event_webLabel5MouseClicked

    private void webLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webLabel5MouseEntered
        // TODO add your handling code here:[255,51,51]
        webLabel5.setBackground(new Color(255, 100, 50));
    }//GEN-LAST:event_webLabel5MouseEntered

    private void webLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webLabel5MouseExited
        // TODO add your handling code here:
        webLabel5.setBackground(new Color(255,154,59));
    }//GEN-LAST:event_webLabel5MouseExited

    private void webButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webButton1ActionPerformed
        // TODO add your handling code here:
        new BookReader("H:\\Library\\Books Library\\Encyclopedia\\The Cat Encyclopedia - The Definitive Visual Guide (2014).pdf").setVisible(true);
    }//GEN-LAST:event_webButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        WebLookAndFeel.install();
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookShelf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.alee.laf.button.WebButton webButton1;
    private com.alee.laf.label.WebLabel webLabel1;
    private com.alee.laf.label.WebLabel webLabel2;
    private com.alee.laf.label.WebLabel webLabel3;
    private com.alee.laf.label.WebLabel webLabel4;
    private com.alee.laf.label.WebLabel webLabel5;
    private com.alee.laf.label.WebLabel webLabel6;
    private com.alee.laf.panel.WebPanel webPanel1;
    private com.alee.laf.panel.WebPanel webPanel10;
    private com.alee.laf.panel.WebPanel webPanel2;
    private com.alee.laf.panel.WebPanel webPanel3;
    private com.alee.laf.panel.WebPanel webPanel4;
    private com.alee.laf.panel.WebPanel webPanel5;
    private com.alee.laf.panel.WebPanel webPanel6;
    private com.alee.laf.panel.WebPanel webPanel7;
    private com.alee.laf.panel.WebPanel webPanel8;
    private com.alee.laf.panel.WebPanel webPanel9;
    // End of variables declaration//GEN-END:variables
}
